### ISSUE TITLE
Restart issue

### ISSUE THREAD

**Issue by Arcticguy867** [vipexee/Forced-First-Person#6]
I am having a issue that i have to restart the script for it to work 

It won't work if i restart the server 

If i restart the script and i relog after that i won't again for it to work i need to restart it again and i can't rejoin because if i leave and rejoin it breaks again

**Comment by 0ddShot1** [comment]
Having the same issue, This is the only script I found to work on bikes.

**Comment by vipexv** [comment]
Not sure why this would be happening, it wasn't happening before and i haven't touched the code at all except when i added the Bike feature, and even then it was working, i will check this issue out soon, currently busy with another project, but i'll see if i can identify the issue.

**Comment by Arcticguy867** [comment]
local ped = PlayerPedId()
local inVeh = IsPedInAnyVehicle(ped, true)

if Config.Options.ForcedFirst then 
    CreateThread(function()
        while true do
            sleep = 1000
            local _, weapon = GetCurrentPedWeapon(PlayerPedId())
            local unarmed = `WEAPON_UNARMED`
            if weapon == unarmed then
                sleep = 1000
            else
                sleep = 1
                if IsPlayerFreeAiming(PlayerId()) then
                    SetFollowPedCamViewMode(4)
                else
                    SetFollowPedCamViewMode(0)
                end
            end
        Wait(sleep)
        end
    end)
end

if Config.Options.Vehicle then
    CreateThread(function()
        while true do
            sleep = 1000
            local ped = PlayerPedId()
            local bike = IsPedOnAnyBike(ped)
            local _, weapon = GetCurrentPedWeapon(PlayerPedId())
            local unarmed = `WEAPON_UNARMED`
            if IsPedInAnyVehicle(ped) and weapon ~= unarmed then
                sleep = 1
                if IsPedDoingDriveby(ped) then
                    SetFollowVehicleCamViewMode(4)
                else
                    SetFollowVehicleCamViewMode(0)
                end
            else
                sleep = 1000
            end
            Wait(sleep)
        end
    end)
end


if Config.Options.Bike then
    CreateThread(function()
        while true do
            sleep = 1000
            local _, weapon = GetCurrentPedWeapon(PlayerPedId())
            local unarmed = `WEAPON_UNARMED`
            if IsPedOnAnyBike(PlayerPedId()) and weapon ~= unarmed then
                sleep = 1
                if IsControlJustPressed(0, 25) then
                    SetCamViewModeForContext(2, 4)
                elseif IsControlJustReleased(0, 25) then
                    SetCamViewModeForContext(2, 0)
                end
            else
                sleep = 1000
            end
            Wait(sleep)
        end
    end)
end


if Config.EnteringVehicle then
    CreateThread(function()
        if Config.EnteringVehicle then
        while true do
            sleep = 1000
            if IsPedInAnyVehicle(PlayerPedId()) then
                SetFollowPedCamViewMode(4)
                else
                    SetFollowPedCamViewMode(0)
                if GetPedInVehicleSeat(inVeh, -1) then
                    SetFollowVehicleCamViewMode(4)
                        end
                    end
                Wait(sleep)
            end
        end
    end)
end










Here use this replace the main with this

**Comment by Arcticguy867** [comment]
> Having the same issue, This is the only script I found to work on bikes.

solution ^^^

**Comment by vipexv** [comment]
How would this fix it tho, what even was the issue in the first place?

**Comment by vipexv** [comment]
Should be fixed.
